### ISSUE TITLE
Check improvement of metrics under nodetriangles

### ISSUE THREAD

**Issue by wangzun66** [UPB-Lemming-Group/Lemming#11]

**Comment by Hollowfier** [comment]
NullPointerException occured while executing the graph amendment phase

INFO [org.aksw.simba.lemming.mimicgraph.generator.GraphOptimization] - <Start optimize the mimic graph!>
Exception in thread "main" java.lang.NullPointerException
at toools.collections.LucIntSets.union(LucIntSets.java:62)
at grph.Grph.getEdgesIncidentTo(Grph.java:2108)
at org.aksw.simba.lemming.ColouredGraph.getEdgesIncidentTo(ColouredGraph.java:724)
at org.aksw.simba.lemming.metrics.single.nodetriangles.NodeTriangleMetric.update(NodeTriangleMetric.java:47)
at org.aksw.simba.lemming.metrics.single.edgemanipulation.EdgeModifier.tryToRemoveAnEdge(EdgeModifier.java:88)
at org.aksw.simba.lemming.mimicgraph.generator.GraphOptimization.refineGraph(GraphOptimization.java:91)
at org.aksw.simba.lemming.tools.GraphGenerationTest.main(GraphGenerationTest.java:247)
